"""empty message

Revision ID: 26c642e1c7a5
Revises: c3ad4be9db77
Create Date: 2024-06-16 17:14:31.135841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26c642e1c7a5'
down_revision = 'c3ad4be9db77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
