"""empty message

Revision ID: 2cf5561a0bf6
Revises: 4a9b4f96e227
Create Date: 2024-06-16 22:37:07.190285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cf5561a0bf6'
down_revision = '4a9b4f96e227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Suscripcion', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Suscripcion', schema=None) as batch_op:
        batch_op.alter_column('logo',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
