"""empty message

Revision ID: 4a9b4f96e227
Revises: 6e38074b9f05
Create Date: 2024-06-16 17:45:55.611879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a9b4f96e227'
down_revision = '6e38074b9f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.drop_index('correo')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index('correo', ['correo'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
