"""empty message

Revision ID: 6e38074b9f05
Revises: 26c642e1c7a5
Create Date: 2024-06-16 17:39:34.576501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e38074b9f05'
down_revision = '26c642e1c7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=255), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
