"""empty message

Revision ID: c3ad4be9db77
Revises: b1691760deec
Create Date: 2024-06-16 17:13:50.627937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3ad4be9db77'
down_revision = 'b1691760deec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
